"""Writes two Lean files from data/species.yaml, neither edited by hand:

- lean/IGC/Generated/Table.lean: the species rows, the content built from its parts
  (`smContent`), and the branches as instances of it.
- lean/IGC/Generated/Expected.lean: every count Python computes for each branch, as
  Lean literals. lean/IGC/Agreement.lean proves Lean's own evaluation equals each
  one, so `lake build` fails if Python and Lean ever disagree.

tests/test_codegen.py checks both are byte-identical to a fresh regeneration, so
neither can drift from species.yaml or from count.py/horizon.py.

Curvature traces are written as an integer numerator and a positive natural
denominator; multiplicities as naturals. Table.lean needs no Mathlib import.
"""
from __future__ import annotations

import hashlib
import pathlib
from fractions import Fraction

from igc import count, horizon, sensitivity, table

ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATED_DIR = ROOT / "lean" / "IGC" / "Generated"
TABLE_PATH = GENERATED_DIR / "Table.lean"
EXPECTED_PATH = GENERATED_DIR / "Expected.lean"


def _species_hash(path: pathlib.Path = table.SPECIES_PATH) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _lower_camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part.capitalize() for part in rest)


def branch_ident(branch_name: str) -> str:
    return "branch" + "".join(part.capitalize() for part in branch_name.split("_"))


def _header(species_hash: str) -> list[str]:
    return [
        "/-",
        "GENERATED by src/igc/codegen.py from data/species.yaml -- do not edit.",
        f"Hash of data/species.yaml: {species_hash}",
        "-/",
    ]


def generate_table(species_path: pathlib.Path = table.SPECIES_PATH) -> str:
    species = table.load_species(species_path)
    species_hash = _species_hash(species_path)

    lines = _header(species_hash) + [
        "",
        "namespace IGC.Generated",
        "",
        f'def tableHash : String := "{species_hash}"',
        "",
        "/-- One species as the count reads it. `curvatureNum / curvatureDen` is the",
        "curvature trace of the species' own operator. -/",
        "structure SpeciesRow where",
        "  sign : Int",
        "  components : Int",
        "  curvatureNum : Int",
        "  curvatureDen : Nat",
        "  entanglement : Int",
        "  contact : Int",
        "deriving Repr, DecidableEq",
        "",
        "/-- A content: each species with its multiplicity. -/",
        "abbrev Branch := List (SpeciesRow × Nat)",
        "",
    ]
    for name, s in species.items():
        frac = s.curvature_trace
        lines.append(
            f"def {_lower_camel(name)} : SpeciesRow :=\n"
            f"  {{ sign := {s.statistics_sign}, components := {s.real_components}, "
            f"curvatureNum := {frac.numerator}, curvatureDen := {frac.denominator},\n"
            f"    entanglement := {s.entanglement}, contact := {s.contact} }}"
        )
        lines.append("")
    content = table.load_content(species_path)
    entries = ", ".join(f"({_lower_camel(n)}, {_multiplicity_expr(content, n)})" for n in species)
    sm = (content.standard_model_generations, content.standard_model_doublets)
    lines += [
        "/-- The content with `g` generations, `h` Higgs doublets and `nu` right-handed",
        "neutrinos, from its parts (the content block of `data/species.yaml`). -/",
        "def smContent (g h nu : Nat) : Branch :=",
        f"  [{entries}]",
        "",
    ]
    for branch_name, nu in table.branch_neutrinos(species_path).items():
        lines.append(f"def {branch_ident(branch_name)} : Branch := smContent {sm[0]} {sm[1]} {nu}")
    lines += ["", "end IGC.Generated", ""]
    return "\n".join(lines)


def _multiplicity_expr(content: table.Content, name: str) -> str:
    """A species' multiplicity in `smContent g h nu`, as a Lean expression over the
    content's parts -- the same sum `table.Content.multiplicity` computes."""
    terms = []
    if content.gauge_group.get(name):
        terms.append(str(content.gauge_group[name]))
    if content.per_gauge_vector.get(name):
        terms.append(f"{content.per_gauge_vector[name]} * {content.gauge_vectors}")
    for var, per in (("g", content.per_generation), ("h", content.per_doublet),
                     ("nu", content.per_right_handed_neutrino)):
        k = per.get(name, 0)
        if k:
            terms.append(var if k == 1 else f"{k} * {var}")
    return " + ".join(terms) or "0"


def _rat_literal(x: Fraction) -> str:
    if x.denominator == 1:
        return f"({x.numerator} : ℚ)"
    return f"({x.numerator} / {x.denominator} : ℚ)"


def expected_values(species_path: pathlib.Path = table.SPECIES_PATH) -> dict[str, dict[str, Fraction]]:
    """Every quantity Agreement.lean checks, per branch, as Python computes it."""
    species = table.load_species(species_path)
    branches = table.load_branches(species_path)
    out = {}
    for branch_name, mult in branches.items():
        K, I = count.totals(species, mult)
        c = count.criterion(K, I)
        Ent, Con = horizon.totals(species, mult)
        out[branch_name] = {
            "kinetic": K,
            "insertion": I,
            "net": c["net"],
            "threshold": c["threshold"],
            "entanglement": Ent,
            "contact": Con,
            "couplingBound": count.coupling_bound(species, mult),
            "conformalCount": count.net_with_coupling(species, mult,
                                                      sensitivity.CONFORMAL_COUPLING),
        }
    return out


def extension_counts(species_path: pathlib.Path = table.SPECIES_PATH) -> dict[str, Fraction]:
    """The Standard Model's count with one further gauge vector, alone and with a complex
    scalar, as Python computes it (`Content.extension`)."""
    species = table.load_species(species_path)
    content = table.load_content(species_path)
    out = {}
    for name, (vectors, scalars) in {"OneBoson": (1, 0), "OneBosonAndScalars": (1, 2)}.items():
        K, I = count.totals(species, content.extension(species, vectors, scalars))
        out[name] = K + I
    return out


def generate_expected(species_path: pathlib.Path = table.SPECIES_PATH) -> str:
    values = expected_values(species_path)
    lines = ["import Mathlib.Data.Rat.Defs", ""] + _header(_species_hash(species_path)) + [
        "",
        "/-! Python's values for every count, one per branch and quantity. Agreement.lean",
        "proves Lean's own evaluation over the generated table equals each. -/",
        "",
        "namespace IGC.Generated.Expected",
        "",
    ]
    for branch_name, quantities in values.items():
        suffix = branch_ident(branch_name)[len("branch"):]
        for qty, value in quantities.items():
            lines.append(f"def {qty}{suffix} : ℚ := {_rat_literal(value)}")
        lines.append("")
    for g, value in generation_counts(species_path).items():
        lines.append(f"def net{g}Generations : ℚ := {_rat_literal(value)}")
    lines.append("")
    for name, value in extension_counts(species_path).items():
        lines.append(f"def net{name} : ℚ := {_rat_literal(value)}")
    lines += ["", "end IGC.Generated.Expected", ""]
    return "\n".join(lines)


def generation_counts(species_path: pathlib.Path = table.SPECIES_PATH) -> dict[int, Fraction]:
    """The net count with one Higgs doublet and no right-handed neutrino, for zero up to
    the Standard Model's number of generations, as Python computes it."""
    species = table.load_species(species_path)
    content = table.load_content(species_path)
    out = {}
    for g in range(content.standard_model_generations + 1):
        mult = content.multiplicities(species, g, content.standard_model_doublets)
        K, I = count.totals(species, mult)
        out[g] = K + I
    return out


def write(species_path: pathlib.Path = table.SPECIES_PATH) -> list[pathlib.Path]:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    TABLE_PATH.write_text(generate_table(species_path), encoding="utf-8")
    EXPECTED_PATH.write_text(generate_expected(species_path), encoding="utf-8")
    return [TABLE_PATH, EXPECTED_PATH]


if __name__ == "__main__":
    for path in write():
        print(f"wrote {path}")
