r"""`make latex`: the paper's feed, written to build/latex/ from results/ and the registry.

- numbers.tex: one `\newcommand` per `emit.macros()` entry, so a regenerated result
  changes the paper's numbers without touching its source;
- gallery.tex: every one of those commands typeset, for the test document, so a value
  that does not compile cannot hide in a macro nothing yet uses;
- tables/*.tex: booktabs tabulars, read only from results/*.json, data/ and the claims
  registry. Each file's first line says which float it needs (`table` or `table*`); the
  float is the paper's, the tabular is the feed's;
- refs.bib: data/references.yaml, so the paper and the documents cite identically.

No siunitx: under revtex4-2 it breaks `p{}` columns in this toolchain, so numbers are
set as plain text, as in the generated documents.
"""
from __future__ import annotations

import json
import pathlib
import re
from fractions import Fraction

from igc import claims, emit, table

ROOT = pathlib.Path(__file__).resolve().parents[2]
LATEX_DIR = ROOT / "build" / "latex"
RESULTS_DIR = ROOT / "results"

_NAME = re.compile(r"^[A-Za-z]+$")
_SIGNED = re.compile(r"^[+−]\d+$")
_FRACTION = re.compile(r"^−?\d+/\d+$")
_TEX_SPECIAL = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
                "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\^{}"}
_TEX_SPECIAL_RE = re.compile("|".join(re.escape(k) for k in _TEX_SPECIAL))
# Characters the documents use that pdflatex's default encoding does not carry.
_UNICODE = {"−": "$-$", "≈": "$\\approx$", "≤": "$\\le$", "≥": "$\\ge$",
            "ξ": "$\\xi$", "ρ": "$\\rho$", "Λ": "$\\Lambda$", "π": "$\\pi$"}


def latex_safe_name(key: str) -> str:
    """A LaTeX control sequence of letters only. A macro name that fails is a bug in
    `emit.macros()`, caught here rather than as an undefined control sequence."""
    if not _NAME.match(key):
        raise ValueError(f"macro {key!r} is not a valid LaTeX command name (letters only)")
    return key


def tex_escape(s: str) -> str:
    """Free text from data/ or the registry, safe outside math mode."""
    out = _TEX_SPECIAL_RE.sub(lambda m: _TEX_SPECIAL[m.group(0)], str(s))
    for ch, rep in _UNICODE.items():
        out = out.replace(ch, rep)
    return out


def tex_value(v: str) -> str:
    """A macro's text as LaTeX: counts and fractions in math, `%` escaped."""
    if _SIGNED.match(v) or _FRACTION.match(v):
        return "\\ensuremath{" + v.replace("−", "-") + "}"
    return tex_escape(v)


def _signed(x) -> str:
    """A count in a table: signed, except zero."""
    if Fraction(x) == 0:
        return "$0$"
    return "$" + emit.signed(x).replace("−", "-") + "$"


def _frac(x) -> str:
    x = Fraction(x)
    if x.denominator == 1:
        return f"${x.numerator}$"
    return f"${x.numerator}/{x.denominator}$"


def _load(name: str) -> dict:
    return json.loads((RESULTS_DIR / f"{name}.json").read_text(encoding="utf-8"))


# ------------------------------------------------------------------ numbers
def numbers_tex(m: dict[str, str]) -> str:
    lines = ["% GENERATED by igc.latex from results/ -- do not edit.", ""]
    for key in sorted(m):
        lines.append(f"\\newcommand{{\\{latex_safe_name(key)}}}{{{tex_value(m[key])}}}")
    return "\n".join(lines) + "\n"


def gallery_tex(m: dict[str, str]) -> str:
    lines = ["% GENERATED by igc.latex -- every command in numbers.tex, typeset.", "",
             "{\\small"]
    for key in sorted(m):
        # \char92 is typewriter's own backslash glyph (\textbackslash would substitute).
        lines.append(f"\\noindent\\texttt{{\\char92 {key}}}\\hfill\\{key}\\par")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------- tables
_SPECIES_NAME = {"minimal_scalar": "minimal scalar", "weyl_fermion": "Weyl fermion",
                 "vector": "gauge vector", "ghost": "ghost"}


def _tabular(spec: str, header: list[str], rows: list[list[str]], float_: str,
             totals: list[str] | None = None, paragraphs: bool = False) -> str:
    """A booktabs tabular. With `paragraphs`, every cell of a paragraph column is set
    ragged right, so justified text cannot run into the next column, and rows end with
    \\tabularnewline, since \\raggedright redefines \\\\ (and `array`, whose
    \\arraybackslash would fix that, breaks p{} columns under revtex4-2)."""
    end = " \\tabularnewline" if paragraphs else " \\\\"
    cell = (lambda s: "\\raggedright " + s) if paragraphs else (lambda s: s)
    lines = [f"% float: {float_}", "% GENERATED by igc.latex -- do not edit.",
             f"\\begin{{tabular}}{{{spec}}}", "\\toprule",
             " & ".join(cell(h) for h in header) + end, "\\midrule"]
    lines += [" & ".join(cell(c) for c in r) + end for r in rows]
    if totals:
        lines += ["\\midrule", " & ".join(cell(c) for c in totals) + end]
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tables() -> dict[str, str]:
    species = table.load_species()
    count = _load("count")
    sens = _load("sensitivity")
    rows = sens["neutrino_rows"]
    sm_branch = next(b for b, r in rows.items() if r["right_handed_neutrinos"] == 0)
    out = {}

    out["conditions"] = _tabular(
        "@{}p{0.03\\textwidth} p{0.36\\textwidth} p{0.52\\textwidth}@{}",
        ["", "Condition", "Why it matters"],
        [[f"\\textbf{{{k}}}", tex_escape(c), tex_escape(w)]
         for k, (c, w) in claims.CONDITIONS.items()],
        "table*", paragraphs=True)

    out["species"] = _tabular(
        "@{}lrrrrrr@{}",
        ["Species", "$\\sigma$", "$N$", "$c$", "Weight $\\sigma(N-6c)$", "Entanglement",
         "Contact"],
        [[_SPECIES_NAME[n], _signed(s.statistics_sign), str(s.real_components),
          _frac(s.curvature_trace),
          _signed(s.statistics_sign * (s.real_components - 6 * s.curvature_trace)),
          str(s.entanglement), _signed(s.contact)]
         for n, s in species.items()],
        "table*")

    b = count["branches"][sm_branch]
    out["count"] = _tabular(
        "@{}lrrrrrr@{}",
        ["Species", "Multiplicity", "Kinetic", "Insertion", "Weight", "Entanglement",
         "Contact"],
        [[_SPECIES_NAME[n], str(r["multiplicity"]), _signed(r["kinetic"]),
          _signed(r["insertion"]), _signed(r["weight"]), _signed(r["entanglement"]),
          _signed(r["contact"])]
         for n, r in b["by_species"].items()],
        "table*",
        totals=["Total", "", _signed(b["K"]), _signed(b["I"]), _signed(b["net"]),
                _signed(b["entanglement"]), _signed(b["contact"])])

    # The counts by generation are Fig. 1's labelled bars, and each row's cutoff is the
    # magnitude table's, so neither is set again as a table.
    out["neutrinos"] = _tabular(
        "@{}rrrrr@{}",
        ["$\\nu_R$", "Count", "Threshold $\\rho$", "Margin", "Bound on $\\xi$"],
        [[str(r["right_handed_neutrinos"]), _signed(r["net"]), _frac(r["threshold"]),
          emit.pct(r["margin"]).replace("%", "\\%"), _frac(r["coupling_bound"])]
         for name, r in rows.items()],
        "table")

    cut = sens["magnitude"]["cutoff_over_planck"]
    names = {"sharp_step": "sharp step", "heat_kernel": "heat kernel $e^{-u}$",
             "gaussian": "Gaussian $e^{-u^2}$"}
    branches = list(rows)
    k = len(branches)
    lines = ["% float: table", "% GENERATED by igc.latex -- do not edit.",
             f"\\begin{{tabular}}{{@{{}}lr{'r' * k}@{{}}}}", "\\toprule",
             f" & & \\multicolumn{{{k}}}{{c}}{{$\\Lambda/M_P$}} \\\\",
             f"\\cmidrule(l){{3-{2 + k}}}",
             "Profile & $M_f$ & " + " & ".join(
                 f"$\\nu_R={rows[b]['right_handed_neutrinos']}$" for b in branches) + " \\\\",
             "\\midrule"]
    for p, M in sens["magnitude"]["moments"].items():
        moment = str(int(M)) if float(M).is_integer() else emit.sig(M)
        lines.append(" & ".join([names[p], moment] + [emit.sig(cut[b][p]) for b in branches])
                     + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    out["magnitude"] = "\n".join(lines) + "\n"

    # Each result's key, the section of the paper it appears in, and the Lean statements
    # it cites. Names never break inside; they break only between one another. The
    # section comes from the paper's \claim{key} markers through \claimsection{key};
    # outside the paper it falls back to a dash.
    rows_lean = [
        [f"\\texttt{{{tex_escape(c['key'])}}}", f"\\claimsection{{{c['key']}}}",
         ", ".join(f"\\texttt{{{tex_escape(n.removeprefix('IGC.'))}}}" for n in c["lean"])]
        for c in claims.CLAIMS if c["kind"] == "claim" and c["lean"]]
    lean = _tabular(
        "@{}p{0.31\\textwidth} p{0.05\\textwidth} p{0.58\\textwidth}@{}",
        ["Result (\\texttt{CLAIMS.md} key)", "Sec.", "Lean statements cited"],
        rows_lean, "table*", paragraphs=True)
    head, rest = lean.split("\\begin{tabular}", 1)
    out["lean"] = head + "\\providecommand{\\claimsection}[1]{--}\n\\begin{tabular}" + rest
    return out



# --------------------------------------------------------------------- bib
_ET_AL = re.compile(r"^(.*?)\s+et al\.\s*(?:\((.*)\))?$")


def _bib_author(name: str) -> tuple[str, str | None]:
    m = _ET_AL.match(name)
    if m:
        return f"{m.group(1)} and others", m.group(2)
    return name, None


def refs_bib() -> str:
    lines = ["% GENERATED by igc.latex from data/references.yaml -- do not edit.", ""]
    for key, r in table.load_references().items():
        authors, collaboration = [], None
        for a in r["authors"]:
            name, collab = _bib_author(a)
            authors.append(name)
            collaboration = collaboration or collab
        lines.append(f"@{r['type']}{{{key},")
        lines.append(f"  author = {{{' and '.join(authors)}}},")
        if collaboration:
            lines.append(f"  collaboration = {{{collaboration}}},")
        lines.append(f"  title = {{{{{tex_escape(r['title'])}}}}},")
        if r["type"] == "misc":
            # revtex prints a @misc's howpublished, not its publisher or version.
            lines.append(f"  howpublished = {{{tex_escape(r['publisher'])}, version "
                         f"{tex_escape(r['version'])}}},")
        for field in ("journal", "volume", "url", "doi"):
            if r.get(field):
                lines.append(f"  {field} = {{{tex_escape(r[field]) if field not in ('doi', 'url') else r[field]}}},")
        if r.get("pages"):
            lines.append(f"  pages = {{{str(r['pages']).replace('-', '--')}}},")
        if r.get("eprint"):
            lines += [f"  eprint = {{{r['eprint']}}},", "  archiveprefix = {arXiv},"]
        lines += [f"  year = {{{r['year']}}},", "}", ""]
    return "\n".join(lines)


# ------------------------------------------------------------------- write
def render_all() -> dict[pathlib.Path, str]:
    m = emit.macros()
    out = {LATEX_DIR / "numbers.tex": numbers_tex(m),
           LATEX_DIR / "gallery.tex": gallery_tex(m),
           LATEX_DIR / "refs.bib": refs_bib()}
    for name, text in tables().items():
        out[LATEX_DIR / "tables" / f"{name}.tex"] = text
    return out


def write_all() -> list[pathlib.Path]:
    written = []
    for path, text in render_all().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


if __name__ == "__main__":
    for p in write_all():
        print(f"wrote {p.relative_to(ROOT)}")
