import IGC

/-!
Not part of the library: `lake env lean Audit.lean` prints the axioms each cited
theorem rests on. CI (`.github/workflows/lean.yml`) fails if any is beyond `propext`,
`Classical.choice` and `Quot.sound`.
-/

#print axioms IGC.Generated.SpeciesRow.weight_eq_kinetic_add_insertion
#print axioms IGC.netTotal_eq_kinetic_add_insertion
#print axioms IGC.TailMeasure.integral_rpow_eq
#print axioms IGC.Profile.derivativeMoment_eq
#print axioms IGC.Profile.insertionMoment_eq
#print axioms IGC.Profile.moment_pos_ofMeasure
#print axioms IGC.Profile.weighting_eq_six
#print axioms IGC.Profile.sharp_f
#print axioms IGC.Profile.sharp_moment
#print axioms IGC.HasA1Coeff.unique
#print axioms IGC.normalizedMoment_heatKernel
#print axioms IGC.ProperTimeProfile.hasDerivAt_F
#print axioms IGC.ProperTimeProfile.moment_eq
#print axioms IGC.ProperTimeProfile.derivativeMoment_eq_gamma
#print axioms IGC.ProperTimeProfile.derivativeMoment_eq
#print axioms IGC.ProperTimeProfile.normalizedMoment_pos
#print axioms IGC.ProperTimeProfile.spectralTrace_eq
#print axioms IGC.ProperTimeProfile.spectralActionA1
#print axioms IGC.heatTrace_map_add
#print axioms IGC.ProperTimeProfile.hasDerivAt_spectralTrace_map_add
#print axioms IGC.ProperTimeProfile.response_hasA1Coeff
#print axioms IGC.ProperTimeProfile.derivativeMoment_div_gamma
#print axioms IGC.one_to_six
#print axioms IGC.InducesNewton.unique
#print axioms IGC.attractive_iff
#print axioms IGC.inducesNewton_of_spectralAction
#print axioms IGC.inducesNewton_properTime
#print axioms IGC.inducesNewton_pos_iff
#print axioms IGC.newton_positive_of_net_pos
#print axioms IGC.netWeight_contentOf
#print axioms IGC.normalizedMoment_pos_ofMeasure
#print axioms IGC.criterion
#print axioms IGC.sm_kinetic
#print axioms IGC.sm_insertion
#print axioms IGC.sm_net
#print axioms IGC.gaugeFieldsCounted_branch0
#print axioms IGC.sm_threshold
#print axioms IGC.sm_margin
#print axioms IGC.sm_criterion_iff
#print axioms IGC.sm_newton_positive
#print axioms IGC.sm_newton_positive_properTime
#print axioms IGC.sm_newton_positive_monotone
#print axioms IGC.net_smContent
#print axioms IGC.generation_counts
#print axioms IGC.generation_floor
#print axioms IGC.unique_count_one
#print axioms IGC.no_count_one_with_neutrinos
#print axioms IGC.net_neutrinos
#print axioms IGC.margin_neutrinos
#print axioms IGC.margin_neutrinos_lt
#print axioms IGC.margin_two
#print axioms IGC.margin_three
#print axioms IGC.generations_newton
#print axioms IGC.neutrinos_newton_positive
#print axioms IGC.cutoff_for_newton
#print axioms IGC.sm_cutoff_for_newton
#print axioms IGC.normalizedMoment_sharp
#print axioms IGC.normalizedMoment_gaussian
#print axioms IGC.normalizedMoment_sharp_four
#print axioms IGC.normalizedMoment_gaussian_four
#print axioms IGC.horizon_agrees_iff
#print axioms IGC.sm_count
#print axioms IGC.sm_attraction_iff
#print axioms IGC.sm_higgs_net
#print axioms IGC.sm_coupled_newton
#print axioms IGC.sm_coupled_newton_properTime
#print axioms IGC.gauge_vector_cost
#print axioms IGC.net_gaugeContent
#print axioms IGC.smContent_eq_gaugeContent
#print axioms IGC.net_smExtension
#print axioms IGC.smExtension_pos_iff
#print axioms IGC.sm_plus_one_boson
#print axioms IGC.sm_plus_boson_and_scalars
#print axioms IGC.extension_newton
#print axioms IGC.sm_conformal_net
#print axioms IGC.sm_conformal_not_attractive
#print axioms IGC.agree_branch0
#print axioms IGC.agree_branch2
#print axioms IGC.agree_branch3
#print axioms IGC.agree_generations
#print axioms IGC.agree_conformal
#print axioms IGC.agree_extensions
